
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
        namespace: c818ac0e-efd4-4424-bbd1-48a38f13cd6e
  application:
    name: service-provider

server:
  port: 8085